name: Opus Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Linux_Build_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone Repository
        run: git clone https://github.com/xiph/opus.git

      - name: Autogen
        run: ./opus/autogen.sh

      - name: Create Build Dir
        run: mkdir build

      - name: Configure
        working-directory: ./build
        run: cmake ../opus -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DOPUS_BUILD_PROGRAMS=ON -DBUILD_TESTING=ON

      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config Release --target package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-libopus.so.0.10.1
          path: ./build/libopus.so.0.10.1

  Linux_Build_x32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Build Libraries
        run: sudo apt-get install g++-multilib

      - name: Clone Repository
        run: git clone https://github.com/xiph/opus.git

      - name: Autogen
        run: ./opus/autogen.sh

      - name: Create Build Dir
        run: mkdir build

      - name: Configure
        working-directory: ./build
        run: cmake ../opus -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DOPUS_BUILD_PROGRAMS=ON -DBUILD_TESTING=ON -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32

      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config Release --target package

      - name: List File
        working-directory: ./build
        run: file ./libopus.so.0.10.1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86-libopus.so.0.10.1
          path: ./build/libopus.so.0.10.1
