name: Opus Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Linux_Build_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone Repository
        run: git clone https://github.com/xiph/opus.git

      - name: Autogen
        run: ./opus/autogen.sh

      - name: Create Build Dir
        run: mkdir build

      - name: Configure
        working-directory: ./build
        run: cmake ../opus -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DOPUS_BUILD_PROGRAMS=ON

      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config Release --target package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86_64-libopus.so.0.10.1
          path: ./build/libopus.so.0.10.1

  Linux_Build_x32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Build Libraries
        run: sudo apt-get install g++-multilib

      - name: Clone Repository
        run: git clone https://github.com/xiph/opus.git

      - name: Autogen
        run: ./opus/autogen.sh

      - name: Create Build Dir
        run: mkdir build

      - name: Configure
        working-directory: ./build
        run: cmake ../opus -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DOPUS_BUILD_PROGRAMS=ON -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32

      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config Release --target package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86-libopus.so.0.10.1
          path: ./build/libopus.so.0.10.1

  Linux_Build_Arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Build Libraries
        run: sudo apt-get install g++-aarch64-linux-gnu

      - name: Clone Repository
        run: git clone https://github.com/xiph/opus.git

      - name: Autogen
        run: ./opus/autogen.sh

      - name: Create Build Dir
        run: mkdir build

      - name: Configure
        working-directory: ./build
        run: cmake ../opus -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DOPUS_BUILD_PROGRAMS=ON -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++

      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config Release --target package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-libopus.so.0.10.1
          path: ./build/libopus.so.0.10.1

  Linux_Build_Arm32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Build Libraries
        run: sudo apt-get install g++-arm-linux-gnueabi

      - name: Clone Repository
        run: git clone https://github.com/xiph/opus.git

      - name: Autogen
        run: ./opus/autogen.sh

      - name: Create Build Dir
        run: mkdir build

      - name: Configure
        working-directory: ./build
        run: cmake ../opus -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DOPUS_BUILD_PROGRAMS=ON -DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabi-g++

      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config Release --target package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm32-libopus.so.0.10.1
          path: ./build/libopus.so.0.10.1
          
  Win_Build_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Build Libraries
        run: sudo apt-get install mingw-w64

      - name: Clone Repository
        run: git clone https://github.com/xiph/opus.git

      - name: Autogen
        run: ./opus/autogen.sh

      - name: Create Build Dir
        run: mkdir build

      - name: Configure
        working-directory: ./build
        run: cmake ../opus -DBUILD_SHARED_LIBS=ON -DOPUS_BUILD_PROGRAMS=ON -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc

      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config Release --target package

      - name: Display File
        run: file ./build/libopus.dll

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-x64-libopus.dll
          path: ./build/libopus.dll

  Win_Build_x32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Build Libraries
        run: sudo apt-get install mingw-w64

      - name: Clone Repository
        run: git clone https://github.com/xiph/opus.git

      - name: Autogen
        run: ./opus/autogen.sh

      - name: Create Build Dir
        run: mkdir build

      - name: Configure
        working-directory: ./build
        run: cmake ../opus -DBUILD_SHARED_LIBS=ON -DOPUS_BUILD_PROGRAMS=ON -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc

      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config Release --target package

      - name: Display File
        run: file ./build/libopus.dll

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-x32-libopus.dll
          path: ./build/libopus.dll
