# This is a basic workflow to help you get started with Actions

name: Speex Compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Build Libraries
        run: sudo apt-get install gcc-multilib g++-multilib

      # Runs a set of commands using the runners shell
      - name: Clone Repository
        run: git clone https://github.com/xiph/speexdsp.git

      - name: Autogen, Configure And Build
        run: ./speexdsp/autogen.sh && ./speexdsp/configure --build=i686-pc-linux-gnu CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 && make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libspeexdsp.so.1.5.2
          path: ./libspeexdsp/.libs/libspeexdsp.1.5.2
