name: Speex Compile

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Build_Arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Build Libraries
        run: sudo apt-get install g++-aarch64-linux-gnu

      - name: Clone Repository
        run: git clone https://github.com/xiph/speexdsp.git

      - name: Autogen
        run: ./speexdsp/autogen.sh

      - name: Configure And Build 64bit ARM
        run: ./speexdsp/configure --host=aarch64-linux-gnu && make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libspeexdsp.so.1.5.2_arm64
          path: ./libspeexdsp/.libs/libspeexdsp.so.1.5.2
          
  Build_Arm32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Build Libraries
        run: sudo apt-get install g++-arm-linux-gnueabi

      - name: Clone Repository
        run: git clone https://github.com/xiph/speexdsp.git

      - name: Autogen
        run: ./speexdsp/autogen.sh

      - name: Configure And Build 32bit ARM
        run: ./speexdsp/configure --host=arm-linux-gnueabi && make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libspeexdsp.so.1.5.2_arm32
          path: ./libspeexdsp/.libs/libspeexdsp.so.1.5.2

  Build_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Build Libraries
        run: sudo apt-get install g++-multilib

      - name: Clone Repository
        run: git clone https://github.com/xiph/speexdsp.git

      - name: Autogen
        run: ./speexdsp/autogen.sh

      - name: Configure And Build 64bit
        run: ./speexdsp/configure CFLAGS=-m64 CXXFLAGS=-m64 LDFLAGS=-m64 && make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libspeexdsp.so.1.5.2_x64
          path: ./libspeexdsp/.libs/libspeexdsp.so.1.5.2

  Build_x32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Build Libraries
        run: sudo apt-get install g++-multilib

      - name: Clone Repository
        run: git clone https://github.com/xiph/speexdsp.git

      - name: Autogen
        run: ./speexdsp/autogen.sh

      - name: Configure And Build 32bit
        run: ./speexdsp/configure CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 && make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: libspeexdsp.so.1.5.2_x64
          path: ./libspeexdsp/.libs/libspeexdsp.so.1.5.2
