name: SpeexDSP Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Win_Build_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Build Libraries
        run: |
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20241015/llvm-mingw-20241015-ucrt-ubuntu-20.04-x86_64.tar.xz
          tar -xf ./llvm-mingw-20241015-ucrt-ubuntu-20.04-x86_64.tar.xz
          rm -rf ./llvm-mingw-20241015-ucrt-ubuntu-20.04-x86_64.tar.xz

      - name: Clone Repository
        run: git clone https://github.com/xiph/speexdsp.git

      - name: Autogen
        run: ./speexdsp/autogen.sh

      - name: Configure And Build 64bit ARM
        run: |
          export TOOLCHAIN=./llvm-mingw-20241015-ucrt-ubuntu-20.04-x86_64
          export TARGET=aarch64-w64-mingw32
          export AR=$TOOLCHAIN/bin/$TARGET-llvm-ar
          export CC="$TOOLCHAIN/bin/$TARGET-clang --target=$TARGET"
          export AS=$CC
          export CXX="$TOOLCHAIN/bin/$TARGET-clang++ --target=$TARGET"
          export LD=$TOOLCHAIN/bin/$TARGET-ld
          export RANLIB=$TOOLCHAIN/bin/$TARGET-llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          ./speexdsp/configure --host $TARGET
          cp -r $TOOLCHAIN ./libspeexdsp
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-arm64-libspeexdsp-1.dll
          path: ./libspeexdsp/.libs/libspeexdsp-1.dll

  Win_Build_arm32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Build Libraries
        run: |
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20241015/llvm-mingw-20241015-ucrt-ubuntu-20.04-x86_64.tar.xz
          tar -xf ./llvm-mingw-20241015-ucrt-ubuntu-20.04-x86_64.tar.xz
          rm -rf ./llvm-mingw-20241015-ucrt-ubuntu-20.04-x86_64.tar.xz

      - name: Clone Repository
        run: git clone https://github.com/xiph/speexdsp.git

      - name: Autogen
        run: ./speexdsp/autogen.sh

      - name: Configure And Build 32bit ARM
        run: |
          export TOOLCHAIN=./llvm-mingw-20241015-ucrt-ubuntu-20.04-x86_64
          export TARGET=armv7-w64-mingw32
          export AR=$TOOLCHAIN/bin/$TARGET-llvm-ar
          export CC="$TOOLCHAIN/bin/$TARGET-clang --target=$TARGET"
          export AS=$CC
          export CXX="$TOOLCHAIN/bin/$TARGET-clang++ --target=$TARGET"
          export LD=$TOOLCHAIN/bin/$TARGET-ld
          export RANLIB=$TOOLCHAIN/bin/$TARGET-llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          ./speexdsp/configure --host $TARGET
          cp -r $TOOLCHAIN ./libspeexdsp
          make

      - name: Display File
        run: file ./libspeexdsp/.libs/libspeexdsp-1.dll

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-arm32-libspeexdsp-1.dll
          path: ./libspeexdsp/.libs/libspeexdsp-1.dll
