name: Speex Compile

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:        
  Win_Build_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone Repository
        run: git clone https://github.com/xiph/speexdsp.git

      - name: Autogen
        run: ./speexdsp/autogen.sh

      - name: Configure And Build Arm64
        run: ./speexdsp/configure CC=clang --host=armv7a-pc-windows --target=armv7a-pc-windows && make

      - name: Display Base Files
        run: dir

      - name: Display Win32 Files
        run: dir ./win32

      - name: Display Files
        run: dir ./libspeexdsp

      - name: Display Lib Files
        run: dir ./libspeexdsp/.libs
